site:
  title: Hos Notes
  start_page: note-base::index.adoc
  url: https://hossein-lap.github.io
  # homeUrl: &home_url /index.html

# page:
#   url: *home_url
#   home: true
#   title: Brand&#8217;s Hardware &amp; Software Requirements

content:
  sources:
  - url: https://github.com/hossein-lap/note-base.git
    branches: devel
    start_path: docs
    weight: 1
  - url: https://github.com/hossein-lap/note-perl.git
    branches: devel
    start_path: docs
    weight: 2
  - url: https://github.com/hossein-lap/note-golang.git
    branches: devel
    start_path: docs
    weight: 2
  - url: https://github.com/hossein-lap/note-git.git
    branches: devel
    start_path: docs
    weight: 2
  # - url: https://github.com/hossein-lap/note-lua.git
  #   branches: devel
  #   start_path: docs
  # - url: https://github.com/hossein-lap/note-shell.git
  #   branches: devel
  #   start_path: docs

ui:
  bundle:
    url: https://github.com/hossein-lap/note-antora-theme/releases/download/prod-latest/ui-bundle.zip?job=bundle-stable
    # url: https://github.com/hossein-lap/asciidoctor-docs-ui/releases/download/prod-351/ui-bundle.zip?job=bundle-stable
    # url: https://gitlab.com/hossein-lap/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    # snapshot: true

# runtime:
#   cache_dir: ./cache/antora

# output:
#   clean: true
#   dir: ./build

asciidoc: 
  attributes: 
    custom-data: ./data.yml
    icons: font
    icon-set: fi
    sectnums: true
    toc: false
    source-highlighter: highlight.js
    # highlightjs-theme: tomorrow-night
    # pygments-style: solarized-light   skip-front-matter: true
    #

